import { check, sleep } from "k6";
import http from "k6/http";

export const options = {
  duration: "30s",
  vus: 1,
  thresholds: {
    http_req_failed: ["rate<0.01"], // http errors should be less than 1%
    http_req_duration: ["p(95)<500"], // 95 percent of response times must be below 500ms
  },
};

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";

function parseJson(body) {
  try {
    return JSON.parse(body);
  } catch (error) {
    return null;
  }
}

export default function () {
  // Health check
  const healthRes = http.get(`${BASE_URL}/api/health`);
  check(healthRes, {
    "health check status is 200": (r) => r.status === 200,
  });

  // Create a new bug
  const payload = JSON.stringify({
    title: `Test Bug ${Date.now()}`,
    description: "This is a test bug created by k6",
    priority: "Medium",
    status: "Open",
  });

  const headers = { "Content-Type": "application/json" };

  const createBugRes = http.post(`${BASE_URL}/api/bugs`, payload, {
    headers,
  });

  check(createBugRes, {
    "create bug status is 201": (r) => r.status === 201,
    "bug has an id": (r) => {
      const body = parseJson(r.body);
      return body !== null && body.id !== undefined;
    },
  });

  sleep(5);
}

function metricValue(data, metricName, valueName) {
  const metric = data.metrics[metricName];
  return metric && metric.values ? metric.values[valueName] : undefined;
}

function formatNumber(value, digits = 2) {
  return value === undefined ? "n/a" : Number(value).toFixed(digits);
}

function formatPercent(value) {
  return value === undefined ? "n/a" : `${(Number(value) * 100).toFixed(2)}%`;
}

function thresholdRows(data) {
  const rows = [];

  Object.keys(data.metrics).forEach((metricName) => {
    const thresholds = data.metrics[metricName].thresholds || {};

    Object.keys(thresholds).forEach((thresholdName) => {
      rows.push(`
        <tr>
          <td>${metricName}</td>
          <td>${thresholdName}</td>
          <td class="${thresholds[thresholdName].ok ? "pass" : "fail"}">
            ${thresholds[thresholdName].ok ? "PASS" : "FAIL"}
          </td>
        </tr>
      `);
    });
  });

  return rows.length
    ? rows.join("")
    : '<tr><td colspan="3">No thresholds were configured.</td></tr>';
}

function renderHtmlReport(data) {
  const checksRate = metricValue(data, "checks", "rate");
  const failedRate = metricValue(data, "http_req_failed", "rate");
  const durationAvg = metricValue(data, "http_req_duration", "avg");
  const durationP95 = metricValue(data, "http_req_duration", "p(95)");
  const totalRequests = metricValue(data, "http_reqs", "count");
  const iterations = metricValue(data, "iterations", "count");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Performance Test Results</title>
    <style>
      body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
        color: #1f2937;
        background: #f8fafc;
      }
      main {
        max-width: 1100px;
        margin: 0 auto;
        padding: 32px 20px;
      }
      h1 {
        margin: 0 0 8px;
        font-size: 28px;
      }
      .subtitle {
        margin: 0 0 24px;
        color: #64748b;
      }
      .grid {
        display: grid;
        gap: 16px;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      }
      .card {
        border: 1px solid #dbe3ec;
        border-radius: 8px;
        background: #ffffff;
        padding: 18px;
      }
      .label {
        margin-bottom: 8px;
        color: #64748b;
        font-size: 13px;
        text-transform: uppercase;
      }
      .value {
        font-size: 24px;
        font-weight: 700;
      }
      table {
        width: 100%;
        margin-top: 16px;
        border-collapse: collapse;
        background: #ffffff;
        border: 1px solid #dbe3ec;
      }
      th,
      td {
        padding: 12px;
        border-bottom: 1px solid #e5edf5;
        text-align: left;
      }
      th {
        color: #475569;
        background: #eef4f9;
      }
      .pass {
        color: #047857;
        font-weight: 700;
      }
      .fail {
        color: #b91c1c;
        font-weight: 700;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>Performance Test Results</h1>
      <p class="subtitle">Generated by k6 for the Bug Tracker performance stage.</p>

      <section class="grid">
        <div class="card">
          <div class="label">Checks Passed</div>
          <div class="value">${formatPercent(checksRate)}</div>
        </div>
        <div class="card">
          <div class="label">Failed Requests</div>
          <div class="value">${formatPercent(failedRate)}</div>
        </div>
        <div class="card">
          <div class="label">HTTP Duration p95</div>
          <div class="value">${formatNumber(durationP95)} ms</div>
        </div>
        <div class="card">
          <div class="label">HTTP Duration avg</div>
          <div class="value">${formatNumber(durationAvg)} ms</div>
        </div>
        <div class="card">
          <div class="label">Requests</div>
          <div class="value">${formatNumber(totalRequests, 0)}</div>
        </div>
        <div class="card">
          <div class="label">Iterations</div>
          <div class="value">${formatNumber(iterations, 0)}</div>
        </div>
      </section>

      <h2>Thresholds</h2>
      <table>
        <thead>
          <tr>
            <th>Metric</th>
            <th>Threshold</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${thresholdRows(data)}
        </tbody>
      </table>
    </main>
  </body>
</html>`;
}

export function handleSummary(data) {
  const checksRate = metricValue(data, "checks", "rate");
  const failedRate = metricValue(data, "http_req_failed", "rate");
  const durationP95 = metricValue(data, "http_req_duration", "p(95)");

  return {
    "k6-report/index.html": renderHtmlReport(data),
    "k6-report/perf-results.json": JSON.stringify(data, null, 2),
    stdout: [
      "Performance test summary",
      `checks rate: ${formatPercent(checksRate)}`,
      `http request failed rate: ${formatPercent(failedRate)}`,
      `http request duration p95: ${formatNumber(durationP95)}ms`,
    ].join("\n"),
  };
}
