services:
  frontend:
    build:
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    command: sh -c "npm run build && npm start"
