pipeline {
    agent any

    stages {
        stage('Unit Tests Backend') {
            agent {
                docker {
                    image 'golang:1.21-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                   sh 'GOCACHE=/tmp/go-build-cache go test ./... -v 2>&1 | go-junit-report > test-results.xml'
                }
            }
                post {
                    always {
                        junit 'bugtracker-backend/test-results.xml'
                    }
                }
        }

        stage('Unit Tests Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh """
                        npm ci
                        npm run test
                    """
                }
            }
        }
    }

    post {
        always {
            junit 'bugtracker-frontend/test-results.xml'
        }
    }
}