pipeline {
    agent any

    stages {
        stage('Execute Unit Tests') {
            parallel {

                stage('Unit tests backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            args '-u 1000:1000'
                        }
                    }

                    steps {
                        dir('bugtracker-backend') {
                            sh '''
                                                    mkdir -p .cache/go-build
                        mkdir -p .cache/go-mod
                        mkdir -p reports

                        export GOCACHE="$PWD/.cache/go-build"
                        export GOMODCACHE="$PWD/.cache/go-mod"

                        go test -v ./... 2>&1 | go-junit-report > test-results.xml

                        # Generate coverage report
                        go test -coverprofile=coverage.out ./...
                        go tool cover -html=coverage.out -o reports/coverage.html

                            '''
                        }
                    }

                    post {
                        always {
                            junit(
                                testResults: 'bugtracker-backend/test-results.xml',
                                allowEmptyResults: true
                            )

                            publishHTML target: [
                                    reportDir: 'bugtracker-backend/reports',
                                    reportFiles: 'coverage.html',
                                    reportName: 'Backend Coverage Report',
                                ]
                        }
                    }
                }

                stage('Unit tests frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                        }
                    }

                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                            npm ci
                            npm test
                            mkdir -p reports
rm -rf reports/coverage
mv coverage reports/

                        '''
                        }
                    }

                    post {
                        always {
                            junit(
                                testResults: 'bugtracker-frontend/test-results.xml'
                            )

                            publishHTML  target: [
                                    reportDir: 'bugtracker-frontend/reports/coverage',
                                    reportFiles: 'index.html',
                                    reportName: 'Frontend Coverage Report',
                
           
                                ]
                            
                        }
                    }
                }
            }
        }
        stage ("Launch Application"){
                agent{
                    docker{
                        image 'docker:27.5.1'
                        reuseNode true
                        args "-v /var/run/docker.sock:/var/run/docker.sock -u 0"

                    }
                }

                steps{
                    sh '''
                        docker compose up --build -d
                    '''
                }
            }
        
        stage ("Api Tests"){
            agent{
                docker{
                    image 'mcr.microsoft.com/playwright:v1.50.0-focal'
                    reuseNode true
                    args '-u 0 --network=host'
                }
            }
            steps{
                dir('tests-api'){
                    sh "npx wait-port http://localhost:8080/api/health -t 30000"

                    sh 'npm ci'
                    sh "npx playwright test"
                }
            }

        }
    }

   post {
        always {
            cleanWs()
        }
    }
}
