name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    unit-test-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.21'
                cache-dependency-path: bugtracker-backend/go.sum

            - name: Execute Backend Unit Tests
              working-directory: ./bugtracker-backend
              run: |
                go test -v ./...
    unit-test-frontend:
        needs: unit-test-backend
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                node-version: '22'
                cache: 'npm'
                cache-dependency-path: bugtracker-frontend/package-lock.json

            - name: Execute Frontend Unit Tests
              working-directory: ./bugtracker-frontend
              run: |
                npm ci
                npm test
                
            - name: Publish Frontend Test Results
              uses: dorny/test-reporter@v3
              if: always() # Ensure this runs even if tests fail
              with:
                name: Frontend Unit Tests Report
                path: ./bugtracker-frontend/test-results.xml
                reporter: jest-junit