name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Backend tests
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Test backend
        working-directory: ./bugtracker-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./... > test-results.json
          go tool cover -func=coverage.out > coverage.txt

      - name: Generate backend test report
        uses: guyarb/golang-test-annotations@v0.7.0
        if: always()
        with:
          test-results: bugtracker-backend/test-results.json
          package-name: bugtracker-backend

      # Frontend tests
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: bugtracker-frontend/package-lock.json

      - name: Test frontend
        working-directory: ./bugtracker-frontend
        run: npm ci && npm test

      - name: Publish frontend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Tests
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit

  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Use GitHub's Docker Compose setup action
      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Run tests with proper error handling
      - name: Run integration tests
        run: |
          docker-compose up --build --abort-on-container-exit tests || true
          # Capture exit code before docker-compose down
          EXIT_CODE=$(docker-compose ps -q tests | xargs -r docker inspect -f '{{ .State.ExitCode }}')
          # Store exit code since it will be lost after down
          echo $EXIT_CODE > .exit_code
          docker-compose down
          # Read stored exit code
          if [ "$(cat .exit_code)" != "0" ]; then
            exit $(cat .exit_code)
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./tests/playwright-report/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./tests/test-results/*.xml
          retention-days: 30

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration Tests
          path: ./tests/test-results/*.xml
          reporter: jest-junit

      # After integration tests succeed
      - name: Setup performance tests
        if: success()
        run: |
          mkdir -p performance-tests/results
          chmod 777 performance-tests/results

      - name: Run performance tests
        if: success()
        run: |
          docker-compose up --build --abort-on-container-exit performance-tests || true
          EXIT_CODE=$(docker-compose ps -q performance-tests | xargs -r docker inspect -f '{{ .State.ExitCode }}')
          echo $EXIT_CODE > .perf_exit_code
          docker-compose down
          if [ "$(cat .perf_exit_code)" != "0" ]; then
            exit $(cat .perf_exit_code)
          fi

      - name: Upload performance test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./performance-tests/results/results.json
          retention-days: 30
